#!/bin/sh

# Wi-Fi
YOURSSID=X
YOURPASSWORD=X

nmcli dev wifi connect $YOURSSID password $YOURPASSWORD

ping -c 5 8.8.8.8
# GPIO

gpioset gpiochip1 13=1
sleep 1
gpioset gpiochip1 13=0

gpioset gpiochip5 10=1
sleep 1
gpioset gpiochip5 10=0

gpioset gpiochip5 12=1
sleep 1
gpioset gpiochip5 12=0

gpioset gpiochip5 13=1
sleep 1
gpioset gpiochip5 13=0

# SPI
# Due next week

# ADC
# Due next week

